<?xml version="1.0" encoding="UTF-8"?>
<!-- Data generated by EDINA Digimap, University of Edinburgh for icl:3feb29396b7fa3e3 on Tue Sep 16 11:10:28 BST 2013. -->
<!--Created by GO Publisher WFS 3.0.0.5 Build 733cfe0 from 2013-02-26 11:30--><!--Snowflake Software Ltd. (http://www.snowflakesoftware.com)--><osgb:FeatureCollection xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:osgb="http://www.ordnancesurvey.co.uk/xml/namespaces/osgb" xmlns:gml="http://www.opengis.net/gml" xmlns:xlink="http://www.w3.org/1999/xlink" xsi:schemaLocation="http://www.ordnancesurvey.co.uk/xml/namespaces/osgb http://www.ordnancesurvey.co.uk/xml/schema/v6/OSDNFFeatures.xsd">
  <gml:boundedBy>
    <gml:null>unknown</gml:null>
  </gml:boundedBy>
  <osgb:queryTime>2013-09-16T11:10:29</osgb:queryTime>
<osgb:topographicMember>
    <osgb:TopographicPoint fid="osgb1000001770295798">
      <osgb:featureCode>10048</osgb:featureCode>
      <osgb:version>1</osgb:version>
      <osgb:versionDate>2001-11-08</osgb:versionDate>
      <osgb:theme>Land</osgb:theme>
      <osgb:accuracyOfPosition>1.0m</osgb:accuracyOfPosition>
      <osgb:changeHistory>
        <osgb:changeDate>1993-02-01</osgb:changeDate>
        <osgb:reasonForChange>Reclassified</osgb:reasonForChange>
      </osgb:changeHistory>
      <osgb:descriptiveGroup>General Feature</osgb:descriptiveGroup>
      <osgb:descriptiveTerm>Positioned Nonconiferous Tree</osgb:descriptiveTerm>
      <osgb:make>Natural</osgb:make>
      <osgb:physicalLevel>50</osgb:physicalLevel>
      <osgb:point>
        <gml:Point srsName="osgb:BNG">
          <gml:coordinates>541869.6,178866.85</gml:coordinates>
        </gml:Point>
      </osgb:point>
    </osgb:TopographicPoint>
  </osgb:topographicMember>
</osgb:FeatureCollection>
