<?xml version="1.0" encoding="UTF-8"?>
<!-- Data generated by EDINA Digimap, University of Edinburgh for icl:3feb29396b7fa4e4 on Tue Sep 16 11:10:28 BST 2014. -->
<!--Created by GO Publisher WFS 3.0.0.5 Build 734cfe0 from 2014-02-26 11:40--><!--Snowflake Software Ltd. (http://www.snowflakesoftware.com)--><osgb:FeatureCollection xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:osgb="http://www.ordnancesurvey.co.uk/xml/namespaces/osgb" xmlns:gml="http://www.opengis.net/gml" xmlns:xlink="http://www.w3.org/1999/xlink" xsi:schemaLocation="http://www.ordnancesurvey.co.uk/xml/namespaces/osgb http://www.ordnancesurvey.co.uk/xml/schema/v6/OSDNFFeatures.xsd">
  <gml:boundedBy>
    <gml:null>unknown</gml:null>
  </gml:boundedBy>
  <osgb:queryTime>2014-09-16T11:10:29</osgb:queryTime>
<osgb:topographicMember>
    <osgb:TopographicArea fid="osgb1000001771456064">
      <osgb:featureCode>10056</osgb:featureCode>
      <osgb:version>4</osgb:version>
      <osgb:versionDate>2006-02-19</osgb:versionDate>
      <osgb:theme>Land</osgb:theme>
      <osgb:calculatedAreaValue>25.506256</osgb:calculatedAreaValue>
      <osgb:changeHistory>
        <osgb:changeDate>2000-05-17</osgb:changeDate>
        <osgb:reasonForChange>New</osgb:reasonForChange>
      </osgb:changeHistory>
      <osgb:changeHistory>
        <osgb:changeDate>2001-06-25</osgb:changeDate>
        <osgb:reasonForChange>Reclassified</osgb:reasonForChange>
      </osgb:changeHistory>
      <osgb:changeHistory>
        <osgb:changeDate>2003-03-05</osgb:changeDate>
        <osgb:reasonForChange>Reclassified</osgb:reasonForChange>
      </osgb:changeHistory>
      <osgb:descriptiveGroup>General Surface</osgb:descriptiveGroup>
      <osgb:make>Manmade</osgb:make>
      <osgb:physicalLevel>50</osgb:physicalLevel>
      <osgb:polygon>
        <gml:Polygon srsName="osgb:BNG">
          <gml:outerBoundaryIs>
            <gml:LinearRing>
              <gml:coordinates>541749.05,179156.9 541749.1,179158.55 541739.8,179158.45 541739.8,179155.7 541749.1,179155.8 541749.05,179156.9</gml:coordinates>
            </gml:LinearRing>
          </gml:outerBoundaryIs>
        </gml:Polygon>
      </osgb:polygon>
    </osgb:TopographicArea>
  </osgb:topographicMember>
<osgb:topographicMember>
    <osgb:TopographicArea fid="osgb1000042406920">
      <osgb:featureCode>10021</osgb:featureCode>
      <osgb:version>5</osgb:version>
      <osgb:versionDate>2006-02-18</osgb:versionDate>
      <osgb:theme>Buildings</osgb:theme>
      <osgb:calculatedAreaValue>140.582488</osgb:calculatedAreaValue>
      <osgb:changeHistory>
        <osgb:changeDate>1970-01-01</osgb:changeDate>
        <osgb:reasonForChange>New</osgb:reasonForChange>
      </osgb:changeHistory>
      <osgb:changeHistory>
        <osgb:changeDate>2003-03-05</osgb:changeDate>
        <osgb:reasonForChange>Attributes</osgb:reasonForChange>
      </osgb:changeHistory>
      <osgb:changeHistory>
        <osgb:changeDate>2003-09-29</osgb:changeDate>
        <osgb:reasonForChange>Attributes</osgb:reasonForChange>
      </osgb:changeHistory>
      <osgb:descriptiveGroup>Building</osgb:descriptiveGroup>
      <osgb:make>Manmade</osgb:make>
      <osgb:physicalLevel>50</osgb:physicalLevel>
      <osgb:polygon>
        <gml:Polygon srsName="osgb:BNG">
          <gml:outerBoundaryIs>
            <gml:LinearRing>
              <gml:coordinates>541423.2,178958.35 541428.5,178947.75 541437.95,178952.45 541439.1,178953.05 541435.05,178961.15 541433.8,178963.65 541423.2,178958.35</gml:coordinates>
            </gml:LinearRing>
          </gml:outerBoundaryIs>
        </gml:Polygon>
      </osgb:polygon>
    </osgb:TopographicArea>
  </osgb:topographicMember>
</osgb:FeatureCollection>
