<?xml version="1.0" encoding="UTF-8"?>
<!-- Data generated by EDINA Digimap, University of Edinburgh for icl:3feb29396b7fa3e3 on Tue Sep 16 11:10:28 BST 2013. -->
<!--Created by GO Publisher WFS 3.0.0.5 Build 733cfe0 from 2013-02-26 11:30--><!--Snowflake Software Ltd. (http://www.snowflakesoftware.com)--><osgb:FeatureCollection xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:osgb="http://www.ordnancesurvey.co.uk/xml/namespaces/osgb" xmlns:gml="http://www.opengis.net/gml" xmlns:xlink="http://www.w3.org/1999/xlink" xsi:schemaLocation="http://www.ordnancesurvey.co.uk/xml/namespaces/osgb http://www.ordnancesurvey.co.uk/xml/schema/v6/OSDNFFeatures.xsd">
  <gml:boundedBy>
    <gml:null>unknown</gml:null>
  </gml:boundedBy>
  <osgb:queryTime>2013-09-16T11:10:29</osgb:queryTime>
  <osgb:topographicMember>
    <osgb:TopographicArea fid="osgb1000001770298856">
      <osgb:featureCode>10172</osgb:featureCode>
      <osgb:version>5</osgb:version>
      <osgb:versionDate>2008-06-03</osgb:versionDate>
      <osgb:theme>Roads Tracks And Paths</osgb:theme>
      <osgb:calculatedAreaValue>321.162308</osgb:calculatedAreaValue>
      <osgb:changeHistory>
        <osgb:changeDate>2001-06-27</osgb:changeDate>
        <osgb:reasonForChange>New</osgb:reasonForChange>
      </osgb:changeHistory>
      <osgb:changeHistory>
        <osgb:changeDate>2003-03-05</osgb:changeDate>
        <osgb:reasonForChange>Position</osgb:reasonForChange>
      </osgb:changeHistory>
      <osgb:changeHistory>
        <osgb:changeDate>2008-05-03</osgb:changeDate>
        <osgb:reasonForChange>Attributes</osgb:reasonForChange>
      </osgb:changeHistory>
      <osgb:descriptiveGroup>Road Or Track</osgb:descriptiveGroup>
      <osgb:make>Manmade</osgb:make>
      <osgb:physicalLevel>50</osgb:physicalLevel>
      <osgb:polygon>
        <gml:Polygon srsName="osgb:BNG">
          <gml:outerBoundaryIs>
            <gml:LinearRing>
              <gml:coordinates>531711.96,178903.8 531718.7,178909.65 531729.65,178918.25 531723.8,178925.1 531717.65,178932.35 531715.32,178933.97 531702.59,178926.38 531705.3,178920.25 531705.75,178919.15 531705.8,178919.05 531705.8,178918.7 531705.7,178918.35 531705.6,178918.15 531705.35,178917.9 531705.3,178917.8 531705.3,178917.7 531703.7,178917.25 531709.85,178905.5 531710.0,178905.55 531710.6,178905.55 531711.15,178905.3 531711.6,178905.2 531711.8,178905.05 531711.96,178903.8</gml:coordinates>
            </gml:LinearRing>
          </gml:outerBoundaryIs>
          <gml:innerBoundaryIs>
            <gml:LinearRing>
              <gml:coordinates>531713.3,178918.8 531710.3,178928.7 531710.65,178928.65 531712.6,178926.25 531716.2,178921.95 531719.75,178917.7 531720.0,178917.3 531719.6,178917.35 531713.3,178918.8</gml:coordinates>
            </gml:LinearRing>
          </gml:innerBoundaryIs>
        </gml:Polygon>
      </osgb:polygon>
    </osgb:TopographicArea>
  </osgb:topographicMember>
</osgb:FeatureCollection>
