<?xml version="1.0" encoding="UTF-8"?>
<!-- Data generated by EDINA Digimap, University of Edinburgh for icl:3feb29396b7fa3e3 on Tue Sep 16 11:10:28 BST 2013. -->
<!--Created by GO Publisher WFS 3.0.0.5 Build 733cfe0 from 2013-02-26 11:30--><!--Snowflake Software Ltd. (http://www.snowflakesoftware.com)--><osgb:FeatureCollection xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:osgb="http://www.ordnancesurvey.co.uk/xml/namespaces/osgb" xmlns:gml="http://www.opengis.net/gml" xmlns:xlink="http://www.w3.org/1999/xlink" xsi:schemaLocation="http://www.ordnancesurvey.co.uk/xml/namespaces/osgb http://www.ordnancesurvey.co.uk/xml/schema/v6/OSDNFFeatures.xsd">
  <gml:boundedBy>
    <gml:null>unknown</gml:null>
  </gml:boundedBy>
  <osgb:queryTime>2013-09-16T11:10:29</osgb:queryTime>
    <osgb:topographicMember>
    <osgb:TopographicArea fid="osgb1000001771779490">
      <osgb:featureCode>10185</osgb:featureCode>
      <osgb:version>5</osgb:version>
      <osgb:versionDate>2006-02-19</osgb:versionDate>
      <osgb:theme>Structures</osgb:theme>
      <osgb:calculatedAreaValue>51.661488</osgb:calculatedAreaValue>
      <osgb:changeHistory>
        <osgb:changeDate>2003-09-26</osgb:changeDate>
        <osgb:reasonForChange>New</osgb:reasonForChange>
      </osgb:changeHistory>
      <osgb:changeHistory>
        <osgb:changeDate>2004-03-25</osgb:changeDate>
        <osgb:reasonForChange>Attributes</osgb:reasonForChange>
      </osgb:changeHistory>
      <osgb:descriptiveGroup>Structure</osgb:descriptiveGroup>
      <osgb:make>Manmade</osgb:make>
      <osgb:physicalLevel>50</osgb:physicalLevel>
      <osgb:polygon>
        <gml:Polygon srsName="osgb:BNG">
          <gml:outerBoundaryIs>
            <gml:LinearRing>
              <gml:coordinates>541821.25,179390.5 541820.83,179372.87 541820.8,179371.55 541820.7,179365.6 541822.75,179365.55 541822.9,179371.55 541822.93,179373.13 541823.3,179390.45 541821.25,179390.5</gml:coordinates>
            </gml:LinearRing>
          </gml:outerBoundaryIs>
        </gml:Polygon>
      </osgb:polygon>
    </osgb:TopographicArea>
  </osgb:topographicMember>
  <osgb:topographicMember>
    <osgb:TopographicArea fid="osgb1000001771456275">
      <osgb:featureCode>10056</osgb:featureCode>
      <osgb:version>5</osgb:version>
      <osgb:versionDate>2007-03-08</osgb:versionDate>
      <osgb:theme>Land</osgb:theme>
      <osgb:calculatedAreaValue>3129.729976</osgb:calculatedAreaValue>
      <osgb:changeHistory>
        <osgb:changeDate>2000-05-17</osgb:changeDate>
        <osgb:reasonForChange>New</osgb:reasonForChange>
      </osgb:changeHistory>
      <osgb:changeHistory>
        <osgb:changeDate>2001-06-25</osgb:changeDate>
        <osgb:reasonForChange>Reclassified</osgb:reasonForChange>
      </osgb:changeHistory>
      <osgb:changeHistory>
        <osgb:changeDate>2003-03-05</osgb:changeDate>
        <osgb:reasonForChange>Attributes</osgb:reasonForChange>
      </osgb:changeHistory>
      <osgb:changeHistory>
        <osgb:changeDate>2006-11-22</osgb:changeDate>
        <osgb:reasonForChange>Attributes</osgb:reasonForChange>
      </osgb:changeHistory>
      <osgb:descriptiveGroup>General Surface</osgb:descriptiveGroup>
      <osgb:make>Manmade</osgb:make>
      <osgb:physicalLevel>50</osgb:physicalLevel>
      <osgb:polygon>
        <gml:Polygon srsName="osgb:BNG">
          <gml:outerBoundaryIs>
            <gml:LinearRing>
              <gml:coordinates>541696.4,179223.15 541696.8,179218.6 541704.35,179219.35 541704.0,179222.8 541711.45,179223.5 541711.75,179220.05 541711.85,179219.25 541714.05,179219.4 541714.25,179217.45 541712.05,179217.25 541712.95,179206.8 541715.1,179183.15 541715.7,179176.75 541718.4,179176.75 541718.7,179173.6 541768.65,179174.05 541768.35,179206.9 541769.3,179226.7 541727.45,179228.75 541727.2,179223.7 541727.0,179223.75 541726.85,179223.8 541726.75,179223.85 541726.6,179223.95 541726.45,179224.0 541726.25,179224.3 541726.15,179224.4 541726.05,179224.55 541725.9,179224.65 541725.8,179224.75 541725.95,179228.6 541718.28,179229.04 541719.25,179240.4 541719.32,179242.17 541713.8,179242.45 541708.03,179242.67 541703.5,179242.85 541703.25,179237.15 541698.2,179236.6 541692.9,179236.0 541695.2,179234.5 541713.45,179236.55 541714.35,179228.1 541714.7,179225.25 541696.4,179223.15</gml:coordinates>
            </gml:LinearRing>
          </gml:outerBoundaryIs>
          <gml:innerBoundaryIs>
            <gml:LinearRing>
              <gml:coordinates>541726.7,179201.65 541726.35,179191.85 541726.15,179191.9 541726.0,179192.0 541725.45,179192.55 541725.4,179192.65 541725.3,179192.7 541725.25,179192.85 541725.15,179192.95 541725.1,179193.05 541725.2,179200.7 541725.3,179200.85 541725.35,179201.0 541725.5,179201.1 541725.7,179201.3 541725.85,179201.4 541726.0,179201.45 541726.1,179201.55 541726.5,179201.65 541726.7,179201.65</gml:coordinates>
            </gml:LinearRing>
          </gml:innerBoundaryIs>
          <gml:innerBoundaryIs>
            <gml:LinearRing>
              <gml:coordinates>541727.1,179217.45 541726.85,179207.9 541726.55,179207.95 541726.3,179208.0 541726.05,179208.0 541725.95,179208.15 541725.8,179208.35 541725.7,179208.55 541725.6,179208.65 541725.55,179208.75 541725.45,179208.9 541725.45,179209.05 541725.7,179216.9 541725.8,179217.1 541725.95,179217.25 541726.25,179217.35 541726.35,179217.4 541726.65,179217.5 541726.85,179217.5 541727.1,179217.45</gml:coordinates>
            </gml:LinearRing>
          </gml:innerBoundaryIs>
        </gml:Polygon>
      </osgb:polygon>
    </osgb:TopographicArea>
  </osgb:topographicMember>
    <osgb:topographicMember>
    <osgb:TopographicLine fid="osgb1000001771455733">
      <osgb:featureCode>10019</osgb:featureCode>
      <osgb:version>1</osgb:version>
      <osgb:versionDate>2001-11-11</osgb:versionDate>
      <osgb:theme>Buildings</osgb:theme>
      <osgb:theme>Land</osgb:theme>
      <osgb:accuracyOfPosition>1.0m</osgb:accuracyOfPosition>
      <osgb:changeHistory>
        <osgb:changeDate>1993-02-01</osgb:changeDate>
        <osgb:reasonForChange>Reclassified</osgb:reasonForChange>
      </osgb:changeHistory>
      <osgb:descriptiveGroup>Building</osgb:descriptiveGroup>
      <osgb:descriptiveTerm>Outline</osgb:descriptiveTerm>
      <osgb:make>Manmade</osgb:make>
      <osgb:physicalLevel>50</osgb:physicalLevel>
      <osgb:physicalPresence>Overhead</osgb:physicalPresence>
      <osgb:polyline>
        <gml:LineString srsName="osgb:BNG">
          <gml:coordinates>541844.6,179356.2 541844.55,179354.8</gml:coordinates>
        </gml:LineString>
      </osgb:polyline>
    </osgb:TopographicLine>
  </osgb:topographicMember>
    <osgb:topographicMember>
    <osgb:TopographicPoint fid="osgb1000001771454348">
      <osgb:featureCode>10179</osgb:featureCode>
      <osgb:version>3</osgb:version>
      <osgb:versionDate>2003-10-21</osgb:versionDate>
      <osgb:theme>Roads Tracks And Paths</osgb:theme>
      <osgb:accuracyOfPosition>1.0m</osgb:accuracyOfPosition>
      <osgb:changeHistory>
        <osgb:changeDate>1993-02-01</osgb:changeDate>
        <osgb:reasonForChange>Reclassified</osgb:reasonForChange>
      </osgb:changeHistory>
      <osgb:changeHistory>
        <osgb:changeDate>2003-03-05</osgb:changeDate>
        <osgb:reasonForChange>Reclassified</osgb:reasonForChange>
      </osgb:changeHistory>
      <osgb:changeHistory>
        <osgb:changeDate>2003-09-26</osgb:changeDate>
        <osgb:reasonForChange>Attributes</osgb:reasonForChange>
      </osgb:changeHistory>
      <osgb:descriptiveGroup>Roadside</osgb:descriptiveGroup>
      <osgb:descriptiveTerm>Structure</osgb:descriptiveTerm>
      <osgb:make>Manmade</osgb:make>
      <osgb:physicalLevel>50</osgb:physicalLevel>
      <osgb:point>
        <gml:Point srsName="osgb:BNG">
          <gml:coordinates>541866.25,179190.05</gml:coordinates>
        </gml:Point>
      </osgb:point>
    </osgb:TopographicPoint>
  </osgb:topographicMember>
</osgb:FeatureCollection>
